### ISSUE TITLE
Include Comments in Node Hierarchy

### ISSUE THREAD

**Issue by WillBAnders** [WillBAnders/Storm#2]
# Description

The `Node` class should be able to store and set comments that may be present in the configuration. This is necessary in order to re-serializes comments back to the configuration file.

There are two known considerations for implementation:

 - A command can be in various positions relative to a node, such as above (header), aside (inline), or below (footer). This also does not account for block comments that could be in the middle of nodes (`key /*comment*/ = "value"`).
 - Comments vary by configuration format, and some (such as JSON) do not support comments entirely.

### Comment Examples

```js
//file header

//key-a header
key-a = "value" //key-a inline
//key-a footer or key-b header (disambiguate as always header?)
key-b = { //key-b inline?
    //key-b inline 2 or key-c header?
    key-c = "value"
    //key-c footer
} //key-b inline/footer?
//key-b footer

//file footer
```

## Motivation

This is strictly necessary in order to re-serialize comments back to the configuration file, and without this comment information would be lost which certainly does not make for a good user experience.

**Comment by maheshsv** [comment]
I will take , assign to me
